name: build and test

on:
  pull_request:
    branches: [production, staging]

jobs:
  build:
    name: build-test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: yarn
      - name: build
        run: |
          export CI=false
          yarn install --check-files
          yarn build